name: Release
on: 
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_ID: "${{ secrets.DEV_ID }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} BUILD/Build4D.zip
